# IMPORT FROM DOCKERHUB A STABLE PYTHON IMAGE
FROM python:3.7-alpine
# SET MAINTAINER
MAINTAINER Sandoval19
# SET ENVIRONMENT VARIABLES
# ALLOWS TO PYTHON TO DISPLAY ON CONSOLE
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /requirements.txt

RUN pip install -r /requirements.txt 

RUN  mkdir /app
# SET WORKING DIRECTORY
WORKDIR /app
COPY ./app /app

# CREATE A USER TO RUN APPLICATION 
# THIS USER WILL BE ONLY ALLOWED TO EXECUTE
# THIS USER WONT HAVE A HOME DIRECTORY
# THIS IS FOR SECURITY PROPOUSES

RUN adduser -D deploy
USER deploy
